swagger: '2.0'

info:
  version: 0.0.0
  title: Test Service
  description: description
  termsOfService: terms
  contact:
    name: API Team 
    url: http://swagger.io
    email: apiteam@swagger.io
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

basePath: /api

paths:
  /biggie:
    post:
      x-swagger-router-controller: io.swagger.sample.SampleController
      operationId: postMe
      tags:
        - test2
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: 'success!'
          schema:
            $ref: '#/definitions/User'
  /goodbye:
    get:
      x-swagger-router-controller: io.swagger.sample.SampleController
      operationId: goodbye
      tags:
        - test2
      parameters:
        - name: happy
          in: query
          required: true
          type: array
          collectionFormat: csv
          items:
            type: string
      responses:
        '200':
          description: 'success!'
          schema:
            $ref: '#/definitions/User'
  /hello:
    get:
      tags:
        - test1
      operationId: testMe
      parameters:
        - name: limit
          in: query
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: 'fun!'
          schema:
            type: string
      x-swagger-router-controller: io.swagger.sample.SampleController
  '/withModel/{id}':
    get:
      tags:
        - test2
      operationId: withModel
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: 'success!'
          schema:
            $ref: '#/definitions/Animal'
  '/withPath/{id}':
    get:
      tags:
        - test1
      operationId: withPath
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: 'success!'
          schema:
            $ref: '#/definitions/User'
      x-swagger-router-controller: io.swagger.sample.SampleController
definitions:
  User:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    description: 'the name!'
    example: |
      {
        "foo":"bar"
      }
  Address:
    properties:
      street:
        type: string
        example: 12345 El Monte Road
      city:
        type: string
        example: Los Altos Hills
      state:
        type: string
        example: CA
      zip:
        type: string
        example: '94022'
  Animal:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      address:
        $ref: '#/definitions/Address'
    description: 'the name!'
